// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Author struct {
	ID        string  `json:"id"`
	Name      string  `json:"name"`
	Biography string  `json:"biography"`
	Books     []*Book `json:"books"`
}

type Book struct {
	ID      string    `json:"id"`
	Title   string    `json:"title"`
	Price   float64   `json:"price"`
	IsbnNo  bool      `json:"isbn_no"`
	Authors []*Author `json:"authors"`
}
